import type { BloodMarkers } from '@/types';

export type MarkerMetadataField = {
  key: keyof BloodMarkers;
  label: string;
  unit: string;
  placeholder: string;
  hint: string;
  description: string;
  optimalRange: string;
  affects: string;
  foods: string;
  retest: string;
  step?: string;
  category: string;
};

// Shared marker metadata used by both the blood entry bottom sheet
// and the marker detail drawer.
export const MARKER_FIELDS: MarkerMetadataField[] = [
  {
    key: 'glucose',
    label: 'Fasting Glucose',
    unit: 'mg/dL',
    placeholder: '90',
    hint: '70–99',
    description: 'Blood sugar level after fasting. Core metabolic marker.',
    optimalRange: '70–99 mg/dL',
    affects: 'Refined carbs, sleep quality, stress, and activity level.',
    foods: 'Beans, lentils, oats, leafy greens, and protein-forward meals.',
    retest: '8-12 weeks after nutrition and training changes.',
    category: 'Metabolic',
    step: '0.1',
  },
  {
    key: 'hba1c',
    label: 'HbA1c',
    unit: '%',
    placeholder: '5.4',
    hint: '4.0–5.6',
    description: '3-month average blood glucose. Indicates diabetes risk.',
    optimalRange: '4.0–5.6%',
    affects: 'Long-term carb intake, exercise consistency, sleep, and stress.',
    foods: 'High-fiber carbs, legumes, vegetables, and lean proteins.',
    retest: 'Every ~3 months (reflects red blood cell lifespan).',
    category: 'Metabolic',
    step: '0.1',
  },
  {
    key: 'totalCholesterol',
    label: 'Total Cholesterol',
    unit: 'mg/dL',
    placeholder: '180',
    hint: '<200',
    description: 'Combined HDL, LDL, and triglycerides. Key cardiovascular marker.',
    optimalRange: '<200 mg/dL',
    affects: 'Fat quality, fiber intake, genetics, activity, and body weight.',
    foods: 'Oats, beans, nuts, olive oil, fatty fish, and vegetables.',
    retest: '8-12 weeks after diet/lifestyle adjustments.',
    category: 'Cardiovascular',
  },
  {
    key: 'ldl',
    label: 'LDL (Bad Cholesterol)',
    unit: 'mg/dL',
    placeholder: '100',
    hint: '<100',
    description: 'Low-density lipoprotein. Raises heart disease risk at high levels.',
    optimalRange: '<100 mg/dL (optimal)',
    affects: 'Saturated/trans fats, soluble fiber intake, body fat, exercise.',
    foods: 'Oats, barley, psyllium, legumes, fish, and unsalted nuts.',
    retest: '8-12 weeks after targeted nutrition changes.',
    category: 'Cardiovascular',
  },
  {
    key: 'hdl',
    label: 'HDL (Good Cholesterol)',
    unit: 'mg/dL',
    placeholder: '60',
    hint: '>60',
    description: 'High-density lipoprotein. Protective against heart disease.',
    optimalRange: '>60 mg/dL (protective)',
    affects: 'Aerobic training, smoking, body composition, and triglycerides.',
    foods: 'Fatty fish, olive oil, nuts, seeds, and whole-food fats.',
    retest: '8-12 weeks after routine/activity changes.',
    category: 'Cardiovascular',
  },
  {
    key: 'triglycerides',
    label: 'Triglycerides',
    unit: 'mg/dL',
    placeholder: '120',
    hint: '<150',
    description: 'Fat in blood. Elevated levels linked to heart disease risk.',
    optimalRange: '<150 mg/dL',
    affects: 'Refined carbs/sugar, alcohol, insulin resistance, and inactivity.',
    foods: 'Fish, high-fiber carbs, legumes, vegetables, and fewer added sugars.',
    retest: '6-10 weeks after carb quality improvements.',
    category: 'Cardiovascular',
  },
  {
    key: 'apoB',
    label: 'ApoB',
    unit: 'mg/dL',
    placeholder: '80',
    hint: '<90',
    description: 'Apolipoprotein B. One particle per atherogenic lipoprotein; predicts cardiovascular risk better than LDL alone.',
    optimalRange: '<90 mg/dL',
    affects: 'Saturated fat, refined carbs, genetics, body weight, and insulin resistance.',
    foods: 'Oats, legumes, nuts, fatty fish, olive oil, and high-fiber vegetables.',
    retest: '8-12 weeks after lipid-lowering interventions.',
    category: 'Cardiovascular',
  },
  {
    key: 'hsCRP',
    label: 'hs-CRP',
    unit: 'mg/L',
    placeholder: '1.0',
    hint: '<1.0',
    description: 'High-sensitivity C-reactive protein. Measures systemic inflammation linked to cardiovascular risk.',
    optimalRange: '<1.0 mg/L (low risk)',
    affects: 'Body fat, chronic stress, sleep quality, infections, and diet quality.',
    foods: 'Fatty fish, berries, leafy greens, turmeric, nuts, and olive oil.',
    retest: '6-12 weeks after anti-inflammatory lifestyle changes.',
    category: 'Cardiovascular',
    step: '0.1',
  },
  {
    key: 'tsh',
    label: 'TSH',
    unit: 'mIU/L',
    placeholder: '2.0',
    hint: '0.5–4.0',
    description: 'Thyroid-stimulating hormone. Regulates metabolism and energy.',
    optimalRange: '0.5–4.0 mIU/L',
    affects: 'Sleep, stress, iodine/selenium status, illness, and medications.',
    foods: 'Seafood, eggs, dairy, brazil nuts, and adequate protein.',
    retest: '6-12 weeks after therapy or major lifestyle changes.',
    category: 'Hormonal',
    step: '0.01',
  },
  {
    key: 'vitaminD',
    label: 'Vitamin D',
    unit: 'ng/mL',
    placeholder: '30',
    hint: '30–100',
    description: 'Essential for bone health, immunity, and mood regulation.',
    optimalRange: '30–100 ng/mL',
    affects: 'Sun exposure, body fat, dietary intake, and supplementation.',
    foods: 'Salmon, sardines, egg yolks, fortified dairy/alternatives.',
    retest: '8-12 weeks after supplementation changes.',
    category: 'Nutritional',
  },
  {
    key: 'vitaminB12',
    label: 'Vitamin B12',
    unit: 'pg/mL',
    placeholder: '400',
    hint: '300–900',
    description: 'Critical for energy, nerve function, and red blood cells.',
    optimalRange: '300–900 pg/mL',
    affects: 'Animal-food intake, gut absorption, GI health, and medications.',
    foods: 'Eggs, fish, dairy, meat, or fortified foods (if plant-based).',
    retest: '8-12 weeks after targeted intake/supplement updates.',
    category: 'Nutritional',
  },
  {
    key: 'ferritin',
    label: 'Ferritin',
    unit: 'ng/mL',
    placeholder: '50',
    hint: '30–300',
    description: 'Iron storage protein. Indicates iron status and inflammation.',
    optimalRange: '30–300 ng/mL',
    affects: 'Dietary iron, inflammation, blood loss, and absorption quality.',
    foods: 'Red meat, shellfish, legumes, spinach + vitamin C foods.',
    retest: '8-12 weeks after iron strategy changes.',
    category: 'Nutritional',
  },
  {
    key: 'iron',
    label: 'Serum Iron',
    unit: 'mcg/dL',
    placeholder: '80',
    hint: '60–170',
    description: 'Circulating iron. Essential for oxygen transport in blood.',
    optimalRange: '60–170 mcg/dL',
    affects: 'Intake timing, inflammation, blood loss, and absorption.',
    foods: 'Lean red meat, legumes, leafy greens, citrus with iron meals.',
    retest: '6-10 weeks after intake/supplement adjustments.',
    category: 'Nutritional',
  },
  {
    key: 'alt',
    label: 'ALT',
    unit: 'U/L',
    placeholder: '25',
    hint: '0–41',
    description: 'Alanine aminotransferase. Liver enzyme indicating hepatic health.',
    optimalRange: '0–41 U/L (male), 0–33 U/L (female)',
    affects: 'Alcohol, weight gain, medications, processed food load, and sleep.',
    foods: 'High-fiber whole foods, cruciferous vegetables, fish, olive oil.',
    retest: '6-8 weeks after reducing liver stressors.',
    category: 'Hepatic',
  },
  {
    key: 'ast',
    label: 'AST',
    unit: 'U/L',
    placeholder: '22',
    hint: '0–40',
    description: 'Aspartate aminotransferase. Liver and muscle health indicator.',
    optimalRange: '0–40 U/L (male), 0–32 U/L (female)',
    affects: 'Liver strain, intense training, alcohol, and medications.',
    foods: 'Whole-food diet, lean proteins, vegetables, and hydration.',
    retest: '6-8 weeks after recovery and nutrition changes.',
    category: 'Hepatic',
  },
  {
    key: 'albumin',
    label: 'Albumin',
    unit: 'g/dL',
    placeholder: '4.2',
    hint: '3.5–5.5',
    description: 'Protein made by the liver. Reflects nutrition and liver function.',
    optimalRange: '3.5–5.5 g/dL',
    affects: 'Protein intake, liver function, hydration, and inflammation.',
    foods: 'Eggs, fish, poultry, greek yogurt, legumes, and tofu.',
    retest: '8-12 weeks after improving protein/nutrition adequacy.',
    category: 'Hepatic',
    step: '0.1',
  },
  {
    key: 'creatinine',
    label: 'Creatinine',
    unit: 'mg/dL',
    placeholder: '0.9',
    hint: '0.7–1.3',
    description: 'Waste product filtered by kidneys. Indicates kidney function.',
    optimalRange: '0.7–1.3 mg/dL (male), 0.6–1.1 mg/dL (female)',
    affects: 'Hydration, kidney function, muscle mass, and high meat intake.',
    foods: 'Hydration-first approach, balanced protein, less excess sodium.',
    retest: '4-8 weeks if elevated or after hydration changes.',
    category: 'Renal',
    step: '0.01',
  },
  {
    key: 'uricAcid',
    label: 'Uric Acid',
    unit: 'mg/dL',
    placeholder: '5.5',
    hint: '3.5–7.2',
    description: 'Byproduct of purine metabolism. Elevated levels linked to gout and kidney issues.',
    optimalRange: '3.5–7.2 mg/dL (male), 2.6–6.0 mg/dL (female)',
    affects: 'Fructose intake, alcohol, hydration, and purine-rich foods.',
    foods: 'Water, cherries, low-fat dairy, vegetables, and whole grains.',
    retest: '6-10 weeks after diet/hydration adjustments.',
    category: 'Renal',
    step: '0.1',
  },
  {
    key: 'fastingInsulin',
    label: 'Fasting Insulin',
    unit: 'mIU/L',
    placeholder: '5',
    hint: '2–25',
    description: 'Insulin level after fasting. Used to assess insulin resistance (HOMA-IR).',
    optimalRange: '2–6 mIU/L (optimal)',
    affects: 'Refined carb load, sleep, stress, activity, and body fat.',
    foods: 'Protein-forward meals, high-fiber carbs, legumes, and veggies.',
    retest: '6-10 weeks after insulin-sensitivity focused changes.',
    category: 'Metabolic',
    step: '0.1',
  },
  {
    key: 'whiteBloodCells',
    label: 'White Blood Cells',
    unit: 'K/µL',
    placeholder: '6.5',
    hint: '4–11',
    description: 'Total leukocytes. Marker of immune activity and systemic inflammation.',
    optimalRange: '4–11 K/µL',
    affects: 'Acute infection, chronic inflammation, smoking, and stress.',
    foods: 'Anti-inflammatory whole foods, omega-3s, leafy greens, berries.',
    retest: 'Repeat with next CBC; trend matters more than a single value.',
    category: 'Hematology',
    step: '0.1',
  },
  {
    key: 'lymphocytePct',
    label: 'Lymphocytes %',
    unit: '%',
    placeholder: '30',
    hint: '20–40',
    description: 'Lymphocyte share of total WBCs. Drops with chronic stress and aging.',
    optimalRange: '20–40%',
    affects: 'Chronic stress, viral infections, sleep, and aging.',
    foods: 'Protein adequacy, vitamin C, zinc, mushrooms, fermented foods.',
    retest: 'With next CBC.',
    category: 'Hematology',
    step: '0.1',
  },
  {
    key: 'mcv',
    label: 'MCV',
    unit: 'fL',
    placeholder: '90',
    hint: '80–100',
    description: 'Mean corpuscular volume — average size of red blood cells.',
    optimalRange: '80–100 fL',
    affects: 'B12/folate status, alcohol, thyroid, and iron deficiency.',
    foods: 'B12-rich foods (eggs, fish, dairy), leafy greens, legumes.',
    retest: 'With next CBC after nutritional changes.',
    category: 'Hematology',
  },
  {
    key: 'rdw',
    label: 'RDW',
    unit: '%',
    placeholder: '13',
    hint: '11.5–14.5',
    description: 'Red cell distribution width. Higher values track aging and mortality risk.',
    optimalRange: '<13% (optimal), 13–14.5% (normal)',
    affects: 'Iron/B12 deficiency, inflammation, and aging.',
    foods: 'Iron-rich foods, B12, folate, varied whole-food diet.',
    retest: 'With next CBC.',
    step: '0.1',
    category: 'Hematology',
  },
  {
    key: 'alkalinePhosphatase',
    label: 'Alkaline Phosphatase',
    unit: 'U/L',
    placeholder: '75',
    hint: '44–147',
    description: 'Enzyme from liver and bone. Elevated values can flag liver or bone issues.',
    optimalRange: '44–147 U/L',
    affects: 'Liver function, bone turnover, and bile flow.',
    foods: 'Cruciferous vegetables, omega-3s, vitamin D adequacy.',
    retest: '6–8 weeks if elevated and lifestyle changed.',
    category: 'Hepatic',
  },
];

export const MARKER_FIELDS_BY_KEY: Partial<Record<keyof BloodMarkers, MarkerMetadataField>> =
  MARKER_FIELDS.reduce((acc, f) => {
    acc[f.key] = f;
    return acc;
  }, {} as Partial<Record<keyof BloodMarkers, MarkerMetadataField>>);

